version: '3'

services:
  bulk-rna-kallisto-qc:
    build: .
    image: bulk-rna-kallisto-qc
    # number of jobs
    command: "4"
    volumes:
      - /home/pawel/Data/reference-files/kallisto/index_human:/index/:ro
      # either mount all the runs as a single directory
      - /home/pawel/Data/bulk/Project_ALH_LCFA/runs:/input:ro
      # or mount them separately
      # - /home/pawel/Data/bulk/Project_ALH_LCFA/runs/170220/:/input/170220:ro
      # - /home/pawel/Data/bulk/Project_ALH_LCFA/runs/170222/:/input/170222:ro
      # - /home/pawel/Data/bulk/Project_ALH_LCFA/runs/170306/:/input/170306:ro
      - /home/pawel/Data/temp:/output/:rw
