version: '3'

services:
  bulk-rna-kallisto-qc:
    build: .
    image: bulk-rna-kallisto-qc
    # number of jobs
    command: 3
    volumes:
      - /home/pawel/Data/reference-files/kallisto/index_human:/index/:ro
      - /home/pawel/Data/bulk/Project_ALH_LCFA/run_170220/:/input/run1:ro
      - /home/pawel/Data/bulk/Project_ALH_LCFA/run_170222/:/input/run2:ro
      # - /home/pawel/Data/bulk/Project_ALH_LCFA/docker-test/run1:/input/run1:ro
      # - /home/pawel/Data/bulk/Project_ALH_LCFA/docker-test/run2:/input/run2:ro
      - /home/pawel/Data/temp:/output/:rw
